---
# This role is not needed! It's just here for debugging.

- name: proile_dir to make idempotent
  ansible.builtin.file:
    path: "{{profile_dir}}"
    state: directory
    owner: "{{ ansible_env.USER }}"
  become: true

- name: set dynamically
  ansible.builtin.set_fact:
    profile: x11-no-gpu

- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.include_role:
    name: get/xserver

- name: Template profile
  ansible.builtin.template:
    src: "{{profile}}.profile.j2"
    dest: "{{profile_dir}}/x11-no-gpu.profile"

- name: lxc profile edit 
  ansible.builtin.shell: "{{ commands }}"
  args:
    chdir: "{{profile_dir}}"
  loop:
    - "lxc profile create {{profile}}"
    - "cat {{profile}}.profile | lxc profile edit x11-no-gpu"
  loop_control:
    loop_var: commands