---

# Works! has to be cloud image
- name: Create a container
  community.general.lxd_container:
    name: "{{container}}{{num}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      # protocol: lxd
      protocol: simplestreams
      alias: ubuntu/22.04/cloud
    profiles: "['default', '{{profile}}']"
    wait_for_ipv4_addresses: true

- ansible.builtin.include_tasks:
    file: "{{item}}.yml"
  loop:
  - test

- debug:
    msg: "Container {{num}} from {{profile}}"