# Start XWayland in Screen
# https://www.google.com/search?q=ansible+run+command+in+screen
# works!: https://stackoverflow.com/questions/64391742/screen-command-for-ansible

- name: Start XWayland in Screen
  ansible.builtin.shell: "screen -mdSA {{screen_name}} bash -c 'Xwayland -retro -noreset :4'"
  args:
    chdir: "{{config_dir}}"
    creates: xwayland.running
  notify: Touch xwayland.running

- debug:
    msg: |
      To run this manually, use:
        `Xwayland -retro -noreset :{{display_number}}`