# Start XWayland in Screen
# https://www.google.com/search?q=ansible+run+command+in+screen
# works!: https://stackoverflow.com/questions/64391742/screen-command-for-ansible

- name: Is XWayland Running?
  ansible.builtin.shell: "screen -list | grep {{ xwayland_screen_name }}"
  register: xwayland_screen
  failed_when: false
  changed_when: false

- name: Start XWayland in Screen
  ansible.builtin.shell: "screen -mdSA {{ xwayland_screen_name }} bash -c 'Xwayland -retro -noreset :4'"
  when: xwayland_screen.rc == 1
