---

- name: Template preseed file
  ansible.builtin.template:
    src: basic.cfg.j2
    dest: /tmp/basic.cfg

# https://discuss.linuxcontainers.org/t/where-does-lxd-init-store-its-config-selections-file-or-database/11760/4
# if (snap install){ creates: /var/snap/lxd/common/lxd/disks/default.img }

- name: init LXD from preseed
  ansible.builtin.shell: cat basic.cfg | lxd init --preseed
  args:
    chdir: /tmp/
    creates: /var/snap/lxd/common/lxd/disks/default.img
  notify: reboot
