---

- name: Create GPU accelerated Xorg profile
  community.general.lxd_profile:
    name: "x11-gpu-{{ gpu_type }}"
    state: present
    description: GPU accelerated Xorg
    config:
      environment.DISPLAY: :0
      user.user-data: |
        #cloud-config
        runcmd:
          - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
        packages:
          - x11-apps
          - mesa-utils
    devices:
      X0:
        bind: container
        connect: unix:@/tmp/.X11-unix/X{{ host_xserver }}
        listen: unix:@/tmp/.X11-unix/X0
        security.gid: "1000"
        security.uid: "1000"
        type: proxy
      mygpu:
        type: gpu
  when: (gpu_type == 'intel') or (gpu_type == 'amd') or (gpu_type == 'virtio')


# Have an additional profile for Nvidia GPUs!
# when: gpu == 'nvidia'