- name: Create config_dir
  ansible.builtin.file:
    path: "{{config_dir}}"
    state: directory

- name: profile template
  ansible.builtin.include_tasks: from template.yml

# OR
- name: include profile
  ansible.builtin.include_tasks:
    file: "profile/{{ profile_name }}.yml"