- name: Create xwayland-no-gpu.profile
  community.general.lxd_profile:
    name: xwayland-no-gpu.profile
    state: present
    description: unaccelerated Xorg
    config:
      environment.DISPLAY: :{{ display_number }}
      user.user-data: |
        #cloud-config
        runcmd:
          - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
        packages:
          - x11-apps
          - mesa-utils
    devices:
      X{{ display_number }}:
        bind: container
        connect: unix:@/tmp/.X11-unix/X{{ display_number }}
        listen: unix:@/tmp/.X11-unix/X{{ display_number }}
        security.gid: "1000"
        security.uid: "1000"
        type: proxy
