---

# Works! has to be cloud image
- name: Create a container
  community.general.lxd_container:
    name: "{{container}}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      # protocol: lxd
      protocol: simplestreams
      alias: ubuntu/22.04/cloud
    profiles: ["default", "x11-no-gpu"]
    wait_for_ipv4_addresses: true

- name: script to test
  ansible.builtin.lineinfile:
    path: "{{bin_dir}}/xeyeslxd"
    regexp: "^lxc exec {{container}}"
    line: "lxc exec {{container}} -- xeyes"
    mode: '0744'
    create: true