- name: Template preseed file
  ansible.builtin.template:
    src: basic.cfg.j2
    dest: /tmp/basic.cfg

- name: init LXD from preseed
  ansible.builtin.shell: cat basic.cfg | lxd init --preseed
  args:
    chdir: /tmp/
    creates: /var/snap/lxd/common/lxd/disks/default.img
  become: true  # idempotent: Needs to run as root so it can see default.img!
  notify: reboot
