- name: Add LXD container to inventory
  ansible.builtin.blockinfile:
    create: true
    marker_begin: "{{ host_marker }} BEGIN"
    marker_end: "{{ host_marker }} END"
    path: "{{ playbook_dir }}/hosts"
    block: |
      [{{ host_group_name }}]
      {{ container_name }}{{ display_number }}

      [{{ host_group_name }}:vars]
      ansible_connection=lxd