- name: xeyes
  ansible.builtin.lineinfile:
    path: "{{bin_dir}}/xeyes{{num}}"
    regexp: "^lxc exec {{container}}{{num}}"
    line: "lxc exec {{container}}{{num}} -- xeyes"
    mode: '0744'
    create: true

- name: gears
  ansible.builtin.lineinfile:
    path: "{{bin_dir}}/gears{{num}}"
    regexp: "^lxc exec {{container}}{{num}}"
    line: "lxc exec {{container}}{{num}} -- glxgears"
    mode: '0744'
    create: true

- name: connect
  ansible.builtin.lineinfile:
    path: "{{bin_dir}}/connect{{num}}"
    regexp: "^lxc exec {{container}}{{num}}"
    line: "lxc exec {{container}}{{num}} -- sudo -u ubuntu -i"
    mode: '0744'
    create: true