container_name: "test-{{ profile_name }}"

container_image: ubuntu/22.04/cloud

connect_command: "lxc exec {{ container_name }}{{ display_number }} -- sudo -u ubuntu -i"

host_group_name: test_GUI_app_in_LXC

host_marker: "{{ profile_name }}"

xwayland_screen: "xwayland_{{display_number}}"