# Overwrite this in vars/main.yml if you want to *Disable GPU Acceleration.
GPU: true

# Shared between both Host & Container! in Xwayland & @unix socket passthrough in container.profile
# To start Multiple containers: use a loop and increment this number each time!
display_number: 4

# create a LXC profile from template/{{name}}.j2?
from_template: false

inventory_file_base: "{{ playbook_dir }}/inventory/base_container"