---

- name: Create Xwayland GPU accelerated profile
  community.general.lxd_profile:
    name: "{{profile_name}}"
    state: present
    description: Wayland and Xwayland with GPU acceleration
    config:
      environment.DISPLAY: :0
      user.user-data: |
        #cloud-config
        runcmd:
          - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
        packages:
          - x11-apps
          - mesa-utils
    devices:
      wayland-socket:
        bind: container
        connect: unix:/run/user/1000/wayland-{{wayland_socket}}
        listen: unix:/mnt/wayland-socket
        uid: "1000"
        gid: "1000"
        type: proxy
      xwaylandsocket:
        bind: container
        connect: unix:/tmp/.X11-unix/X{{xserver_socket}}
        gid: "1000"
        listen: unix:/mnt/wayland1-X1
        mode: "0777"
        security.gid: "1000"
        security.uid: "1000"
        type: proxy
        uid: "1000"
      mygpu:
        type: gpu
  when: (gpu_type == 'intel') or (gpu_type == 'amd') or (gpu_type == 'virtio')