- name: Kill Xwayland
  ansible.builtin.shell: killall Xwayland
  changed_when: false
  failed_when: false

- name: Delete xwayland.running tmp file
  ansible.builtin.file:
    path: "{{ screen_proc_dir }}/{{xwayland_screen_name}}.running"
    state: absent
