---

- name: container settings
  ansible.builtin.set_fact:
    num: 4
    profile: "x11-no-gpu"
    container: test
    alias: "ubuntu/23.04/cloud"

# Works! has to be cloud image
- name: Create a container
  community.general.lxd_container:
    name: "mycontainer"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams #lxd
      alias: "{{alias}}"
    profiles: "['default', '{{profile}}']"
    wait_for_ipv4_addresses: true
