# Start
- name: Setup & Start Container
  hosts: localhost
  tags: [ start ]
  roles:
  - GUI app/XWayland/Host
  - GUI app/XWayland/Container/create
  - GUI app/XWayland/Container/start Xwayland

# Testing
- name: in Container
  hosts: test_GUI_app_in_LXC
  tags: [ test, xclock, xeyes ]
  roles:
  - GUI app/XWayland/in Container/xclock & eyes
 
- name: connect to Container
  hosts: localhost
  tags: [ test, connect ]
  roles:
  - GUI app/XWayland/Container/connect


# Stop & Clean
- hosts: localhost
  tags: [ stop, never ]
  roles:
  - GUI app/XWayland/clean/stop Container

- hosts: localhost
  tags: [ clean, never ]
  roles:
  - GUI app/XWayland/clean/delete Base Container
  - GUI app/XWayland/clean/delete Profile


# Debug
- name: Debug
  hosts: localhost
  tags: [ debug ]
  vars:
    GPU: true
  roles:
  - GUI app/XWayland/.test/debug